openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:9000
  description: Generated server url
tags:
- name: Actuator
  description: Monitor and interact
  externalDocs:
    description: Spring Boot Actuator Web API Documentation
    url: https://docs.spring.io/spring-boot/docs/current/actuator-api/html/
paths:
  /workflow-engine/workflows/deactivate:
    post:
      tags:
      - workflow-controller
      operationId: deactivateWorkflow
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Workflow"
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "204":
          description: No Content
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "500":
          description: Internal Server Error
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "404":
          description: Not Found
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Workflow"
  /workflow-engine/workflows/activate:
    post:
      tags:
      - workflow-controller
      operationId: activateWorkflow
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                workflow:
                  $ref: "#/components/schemas/Workflow"
                tenant:
                  type: string
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "204":
          description: No Content
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "500":
          description: Internal Server Error
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "404":
          description: Not Found
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Workflow"
  /_/tenant:
    post:
      tags:
      - tenant-controller
      operationId: create
      parameters:
      - name: accept
        in: header
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                tenant:
                  type: string
                attributes:
                  $ref: "#/components/schemas/TenantAttributes"
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "204":
          description: No Content
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "500":
          description: Internal Server Error
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "404":
          description: Not Found
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                type: string
    delete:
      tags:
      - tenant-controller
      operationId: delete
      parameters:
      - name: accept
        in: header
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: string
      responses:
        "400":
          description: Bad Request
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "204":
          description: No Content
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "500":
          description: Internal Server Error
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "404":
          description: Not Found
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "200":
          description: OK
  /admin:
    get:
      tags:
      - Actuator
      summary: Actuator root web endpoint
      operationId: links
      responses:
        "400":
          description: Bad Request
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "204":
          description: No Content
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "500":
          description: Internal Server Error
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "404":
          description: Not Found
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "200":
          description: OK
          content:
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    $ref: "#/components/schemas/Link"
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    $ref: "#/components/schemas/Link"
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    $ref: "#/components/schemas/Link"
  /admin/info:
    get:
      tags:
      - Actuator
      summary: Actuator web endpoint 'info'
      operationId: info
      responses:
        "400":
          description: Bad Request
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "204":
          description: No Content
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "500":
          description: Internal Server Error
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "404":
          description: Not Found
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "200":
          description: OK
          content:
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/json:
              schema:
                type: object
  /admin/health:
    get:
      tags:
      - Actuator
      summary: Actuator web endpoint 'health'
      operationId: health
      responses:
        "400":
          description: Bad Request
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "204":
          description: No Content
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "500":
          description: Internal Server Error
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "404":
          description: Not Found
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "200":
          description: OK
          content:
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/json:
              schema:
                type: object
  /admin/health/**:
    get:
      tags:
      - Actuator
      summary: Actuator web endpoint 'health-path'
      operationId: health-path
      responses:
        "400":
          description: Bad Request
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "204":
          description: No Content
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "500":
          description: Internal Server Error
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "404":
          description: Not Found
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "200":
          description: OK
          content:
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/json:
              schema:
                type: object
  /_/ramls:
    get:
      tags:
      - ramls-controller
      operationId: getRamls
      parameters:
      - name: path
        in: query
        required: false
        schema:
          type: string
      - name: x-okapi-url
        in: header
        required: true
        schema:
          type: string
      - name: accept
        in: header
        required: false
        schema:
          type: string
      responses:
        "400":
          description: Bad Request
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "204":
          description: No Content
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "500":
          description: Internal Server Error
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "404":
          description: Not Found
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                type: object
  /_/jsonSchemas:
    get:
      tags:
      - json-schemas-controller
      operationId: getSchemas
      parameters:
      - name: path
        in: query
        required: false
        schema:
          type: string
      - name: x-okapi-url
        in: header
        required: true
        schema:
          type: string
      - name: accept
        in: header
        required: false
        schema:
          type: string
      responses:
        "400":
          description: Bad Request
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "204":
          description: No Content
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "500":
          description: Internal Server Error
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "404":
          description: Not Found
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ResponseErrors"
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                type: object
components:
  schemas:
    Error:
      required:
      - message
      type: object
      properties:
        message:
          type: string
        type:
          type: string
        code:
          type: string
        parameters:
          type: array
          items:
            $ref: "#/components/schemas/Parameter"
    Parameter:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ResponseErrors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: "#/components/schemas/Error"
        total_records:
          type: integer
          format: int32
    JsonNode:
      type: object
    Node:
      required:
      - name
      type: object
      properties:
        id:
          type: string
        name:
          maxLength: 64
          minLength: 3
          type: string
        description:
          maxLength: 512
          minLength: 0
          type: string
        deserializeAs:
          type: string
          readOnly: true
        identifier:
          type: string
    Setup:
      type: object
      properties:
        asyncAfter:
          type: boolean
        asyncBefore:
          type: boolean
    Workflow:
      required:
      - name
      - versionTag
      type: object
      properties:
        id:
          type: string
        active:
          type: boolean
        deploymentId:
          type: string
        description:
          maxLength: 512
          minLength: 0
          type: string
        historyTimeToLive:
          minimum: 0
          type: integer
          format: int32
        initialContext:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/JsonNode"
        name:
          maxLength: 64
          minLength: 4
          type: string
        nodes:
          type: array
          items:
            $ref: "#/components/schemas/Node"
        setup:
          $ref: "#/components/schemas/Setup"
        versionTag:
          maxLength: 64
          minLength: 1
          type: string
    TenantAttributes:
      type: object
      properties:
        moduleTo:
          type: string
        moduleFrom:
          type: string
    Link:
      type: object
      properties:
        href:
          type: string
        hreflang:
          type: string
        title:
          type: string
        type:
          type: string
        deprecation:
          type: string
        profile:
          type: string
        name:
          type: string
        templated:
          type: boolean
